### ISSUE TITLE
Completely redo /load

### ISSUE THREAD

**Issue by itsmiiolly** [AltitudeMapdev/Issues#61]
(No offense Nathan) but /load was coded pretty horribly. There are tons of bugs and I think some improvements could be made to make life easier.
### Bugs
- The `__MACOSX` folder gets loaded in when it shouldn't
- Bugs with world name limits (eg `The name 'thestrangeboy-2' is longer than the limit of 16 characters`) - this is not longer than 16 chars
- Dropbox uploads seem to break it (needs a village.dat file or something) 
### Suggestions
- Instead of having to rename the folder whenever someone uploads it, automatically rename the folder to the owner's username. For example, if I send in my map and it's called `MyMap`, the plugin should **rename** the folder to `ItsMiiOlly-1` (if `ItsMiiOlly-1` is used, use `ItsMiiOlly-2` etc)

That's all (I think).

**Comment by AustinLMayes** [comment]
Again, this should be in Elevation.

**Comment by itsmiiolly** [comment]
We shouldn't require the `villages.dat` file. It causes errors and it's just hassle. 

```
[08:25:34 WARN]: java.io.FileNotFoundException: ./elevation-tmp/Spider/data/villages.dat (No such file or directory)
[08:25:34 WARN]:        at java.io.FileOutputStream.open(Native Method)
[08:25:34 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
[08:25:34 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
[08:25:34 WARN]:        at it.mapdev.elevation.utils.UnzipUtility.extractFile(UnzipUtility.java:63)
[08:25:34 WARN]:        at it.mapdev.elevation.utils.UnzipUtility.unzip(UnzipUtility.java:43)
[08:25:34 WARN]:        at it.mapdev.elevation.utils.FileUtils.loadFileFromURL(FileUtils.java:74)
[08:25:34 WARN]:        at it.mapdev.elevation.commands.MapCommands.load(MapCommands.java:145)
[08:25:34 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:25:34 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[08:25:34 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:25:34 WARN]:        at java.lang.reflect.Method.invoke(Method.java:606)
[08:25:34 WARN]:        at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
[08:25:34 WARN]:        at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
[08:25:34 WARN]:        at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:409)
[08:25:34 WARN]:        at it.mapdev.elevation.Elevation.onCommand(Elevation.java:50)
[08:25:34 WARN]:        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:51)
[08:25:34 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
[08:25:34 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:730)
[08:25:34 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchServerCommand(CraftServer.java:717)
[08:25:34 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedServer.aB(DedicatedServer.java:296)
[08:25:34 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:261)
[08:25:34 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:559)
[08:25:34 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:472)
[08:25:34 WARN]:        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
```
